version: "3.2"

services:
  drone-server:
    image: drone/drone:1.7
    container_name: drone-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always
    environment:
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_USER_CREATE=username:signalwerk,admin:true
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_USER_FILTER=signalwerk

  drone-agent:
    image: drone/drone-runner-docker:1
    links:
      - drone-server:drone-server
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RUNNER_NAME=local-runner
      - DRONE_RPC_HOST=drone-server:80
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
